repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: pipenv run isort py_code_analyzer
        types: [python]

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: pipenv run black py_code_analyzer
        types: [python]

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: pipenv run flake8
        types: [python]
        exclude: setup.py|pyvis

      - id: mypy
        name: mypy
        stages: [commit]
        language: system
        entry: pipenv run mypy py_code_analyzer
        types: [python]
        pass_filenames: false

      # - id: pytest
      #   name: pytest
      #   stages: [commit]
      #   language: system
      #   entry: pipenv run pytest py_code_analyzer
      #   types: [python]

      # - id: pytest-cov
      #   name: pytest
      #   stages: [push]
      #   language: system
      #   entry: pipenv run pytest --cov py_code_analyzer
      #   types: [python]
      #   pass_filenames: false
